### ISSUE TITLE
Plugin stopped working from 3rd party apps

### ISSUE THREAD

**Issue by mesztam** [sdl/Sdl-Community#358]
Hi,

with this commit:
https://github.com/sdl/Sdl-Community/commit/ce43df8162118fdd092d9af62e6063459159614b

you added a reference to the integration API and ask for the studio instance and a controller here:

`public DeepLMtTranslationProviderLanguageDirection(DeepLMtTranslationProvider deepLMtTranslationProvider, LanguagePair languageDirection)
		{
			_deepLMtTranslationProvider = deepLMtTranslationProvider;
			_languageDirection = languageDirection;
			_options = deepLMtTranslationProvider.Options;
			**_projectsController= SdlTradosStudio.Application.GetController<ProjectsController>();
			var activeFile = _projectsController.CurrentProject.GetSourceLanguageFiles();**
`
This causes an exception if the plugin is tried to be used via the Studio API (e.g. during an analysis task) from a 3rd party application, without starting the Studio UI.

Are these lines really required? It seems that activeFile is not used at all. (Also posted here: https://community.sdl.com/developers-more/developers/language-developers/f/sdk_qa/28966/deepl-plugin-crash-when-running-automatic-tasks-programatically )

thanks,
Tamas

**Comment by mesztam** [comment]
There is another problem in DeepLTranslationProviderConnecter.cs at line 71:

var studioVersion = new Toolkit.Core.Studio().GetStudioVersion().ExecutableVersion;

If executed from a 3rd party application, a FileNotFound exception is thrown at this line.

**Comment by andreaGhisa** [comment]
We fixed this issue in the latest version of the plugin from the AppStore.
