### ISSUE TITLE
Inappropriate GUI control in Advanced Display Filter

### ISSUE THREAD

**Issue by EvzenP** [sdl/Sdl-Community#40]
The radio buttons on "Segment" tab of Advanced Display Filter are inappropriate controls for their purpose.
The problem is that initial state is "**none selected**"... and once user clicks any of the radio buttons, there is no way to 'undo' that action, i.e. to return to the default "none selected" state.
It should be either changed to check boxes (where setting any check box clears all others), or a by-default-selected "All segments" radio button should be added.
![image](https://user-images.githubusercontent.com/14029033/35097614-2915daaa-fc51-11e7-949c-d143c6235c99.png)

**Comment by cromica** [comment]
@andreaGhisa Did we look at this issue?

**Comment by andreaGhisa** [comment]
@cromica I've created an Jira item https://jira.sdl.com/browse/SDLCOM-427. @TinaCaputa will add this option when she finishes the item she's working at this moment.

**Comment by TinaCaputa** [comment]
Hello @EvzenP ,

The requested changes are now live for both Studio 2017 and Studio 2019 versions.
