### ISSUE TITLE
Missing Sdl.Community.Toolkit.Tokenization.dll from Post Edit Compare

### ISSUE THREAD

**Issue by videokojot** [sdl/Sdl-Community#47]
I would like to build Post Edit Compare plugin - but assembly Sdl.Community.Toolkit.Tokenization.dll is missing, so I cannot build. Where can I find it?
Thank you.

**Comment by Impertatore** [comment]
We are in the process of making available a new release of https://github.com/Impertatore/SDL-Studio-Community-Toolkit that will include a helper method to recover the LanguagePlatform representation of ISegmentPair that includes the wordcounts; ensuring that the wordcounts from these apps reflect accurately what is generated from Studio.

I have created a new PR (https://github.com/sdl/Sdl-Community/pull/49) this morning with changes to PE-Compare and Qualitivity that integrates with the updated versions of Sdl.Community.Toolkit.LanguagePlatform.dll and Sdl.Community.Toolkit.Core.dll assemblies.

Until this PR is reviewed and completed, you can clone my fork of the Sdl-Community from: https://github.com/Impertatore/Sdl-Community

Please keep in mind that latest changes to the Toolkit are not released on Github, so until then you will also need to clone and compile https://github.com/Impertatore/SDL-Studio-Community-Toolkit locally and copy the Sdl.Community.Toolkit.LanguagePlatform.dll and Sdl.Community.Toolkit.Core.dll assemblies to the SDL installation directory manually

**Comment by cromica** [comment]
@Impertatore Has this been fixed?

**Comment by Impertatore** [comment]
Hi @cromica, @videokojot,
this issue was resolved towards the end of last year;  all changes related to this are now reflected across all plugins that reference this assembly.
