### ISSUE TITLE
Edit Documentation

### ISSUE THREAD

**Issue by cybersol795** [sdl/Sdl-Community#52]
Would anyone mind if I propose to edit some parts of your documentation? I am taking a technical writing course in university and our assignment involves editing github project documentations to practice real world examples.
The goal is not to significantly change or remove any part of the technical information but to improve the structure of the writing or fix smaller issues such as typos. Edits my involve aspects like clarity and concision too.
It will really help me out if you allow me to contribute, make a few changes and submit a PR. Thanks!

**Comment by cromica** [comment]
No problem. Please send a PR with the proposed changes.
