### ISSUE TITLE
MTEnhanced plugin can't work with Chinese for Microsoft

### ISSUE THREAD

**Issue by jameslao** [sdl/Sdl-Community#58]
Hi, after using the latest 4.0 version with 2019, the MTEnhanced plugin can't work for English <> Chinese for Microsoft API. If you check the MS api (https://docs.microsoft.com/en-us/azure/cognitive-services/translator/languages) it shows the code for Chinese simplified should be **zh-Hans** and for traditional it should be **zh-Hant**. Please correct the code in Sdl.Community.MtEnhancedProvider/MstConnect/ApiConnecter.cs, **convertLangCode** method. Thank you.

**Comment by cromica** [comment]
Thanks @jameslao. We logged this and we'll look into it. We're also welcoming PR's if your willing to make the fix yourself.

**Comment by jameslao** [comment]
@cromica Somehow the SDK won't install on my VS Studio 2017 and SDL 2019 (the installer just closes itself) but that's a different issue. Appreciate if you could work on the fix.

**Comment by jameslao** [comment]
@cromica Just created a PR. Tested OK.
