### ISSUE TITLE
Modify sdlxliff file

### ISSUE THREAD

**Issue by Liguo-Ma** [sdl/Sdl-Community#614]
Hello developers.
I want the code to modify sdlxliff file.
For example I should change targets on sdlxliff file 
Please let me know what source code I should use?

**Comment by andreaGhisa** [comment]
Hi,
You can use the SDL Project Anonymizer to process the xliff: 

https://github.com/sdl/Sdl-Community/tree/master/SDLDataProtectionSuite/SDLDataProtectionSuite/SdlProjectAnonymizer
