### ISSUE TITLE
[Feature] Batch Search Replace in TARGET

### ISSUE THREAD

**Issue by drkhateeb** [sdl/Sdl-Community#689]
Hello dear developer

I suggest adding Batch Search replace in Target also
it could be some tool like this 

![sdlxliff-batch](https://user-images.githubusercontent.com/161371/102142563-aa0be700-3e73-11eb-9eee-673004300124.jpg)

Rationale:
QA with auto fix errors (spacing, punctuation,etc. 
Replace terms
Correct minor and repeated errors in the target

Regards

**Comment by andreaGhisa** [comment]
Hi @drkhateeb,

Thank you for the enhancement suggestion. Can you please post this feature suggestion to ideas.sdl.com?

I'll close this thread because is not referring to any plugin from this repository.
