### ISSUE TITLE
NLog - log hijacking?

### ISSUE THREAD

**Issue by adicl** [sdl/Sdl-Community#742]
Hello,
Inspired by your nice plugins, I also added NLog to one of my Studio plugins, and the logging seemed to work nicely.
Unfortunately, after some weeks, suddenly my log entries started missing?!?! On Studio's start, after the plugin was loaded, logging was fine but after a few seconds the logging stopped?!?! 
After some investigation I realized that after some seconds my log entries were redirected into **%APPDATA%\SDL\ExcelTerminologyProvider\ExcelTerminologyProvider.txt** 😀 so apparently the problem was caused by the TermExcelerator plugin I installed some days ago.
Indeed, the culprit seems  to be the "*" in the rule matching pattern which applies the rule to all the loggers:
https://github.com/sdl/Sdl-Community/blob/5ade4162f7108b18524d7e9faea613ee25bba922/TermExcelerator/Sdl.Community.TermExcelerator/Services/Log.cs#L40
Unfortunately the same code is used for several plugins... so I guess the same fix should be applied everywhere:
https://github.com/sdl/Sdl-Community/search?q=new+LoggingRule%28%22*%22

**Comment by andreaGhisa** [comment]
Hi @adicl,
Sorry for the inconvenience, we updated a couple of plugins configuration until now, however, we didn't manage to update all of them. 

I've created a story in Jira under this number(https://jira.sdl.com/browse/SDLCOM-2690) for this issue. Based on the availability we'll update all the remaining plugins.

Kind regards,
Andrea Ghisa
