### ISSUE TITLE
ApplyStudioProjectTemplate does not import Terminology server URI correctly

### ISSUE THREAD

**Issue by desautel** [sdl/Sdl-Community#8]
In  Sdl-Community/ApplyStudioProjectTemplate/Sdl.Community.ApplyStudioProjectTemplate/ApplyStudioProjectTemplateAction.cs

Line 264: targetProject.UpdateTermbaseConfiguration(targetTermbaseConfig);
this function does not work correctly with server URI:
- when a server termbase is set, you will find following line in sdlproj:
  &lt;Path&gt;https://MTserver.company.de/\%\Customer&lt;/Path&gt;
- when you run the app and wish to get this Path in your new project, it inserts:
  &lt;Path&gt;MTserver.company.de\%\Customer&lt;/Path&gt;

With this setting, the terminology does not work. In the Multiterm settings, the TM are marked with a red cross. You have to load the termbase again.

This problem lies in the UpdateTermbaseConfiguration() function.

**Comment by cromica** [comment]
Did you check if the targetTermbaseConfig object has the correct value before calling UpdateTermbaseConfiguration ?

**Comment by desautel** [comment]
Yes, I checked everything. The value is correct before the UpdateTermbase Configuration and I actually haven't found any difference with the Server-Object after the Update. It's when the server URI is written in the sdlproj file that the problem occurs.

**Comment by cromica** [comment]
I raised a new internal issue for the development team to look at this issue - LG-7295

**Comment by andreaGhisa** [comment]
This issue was fixed.
![image](https://user-images.githubusercontent.com/16224379/55934841-a190f100-5c3a-11e9-98e2-b8c50ff6e57c.png)
