### ISSUE TITLE
MT Enhanced Provider does not work with Deployed MSFT Custom Translator v3 Engines

### ISSUE THREAD

**Issue by ayanishevsky** [sdl/Sdl-Community#92]
Hello, 
I tried in SDL Trados Studio 2017 and indicated a deployed engine from MSFT Custom Translator under Category ID. 
The output was from generic Bing. 
Perhaps there is a bug in using deployed customized engines in v3? 

Thanks, Alex

**Comment by cromica** [comment]
@andreaGhisa have we tested with a similar scenario?
