### ISSUE TITLE
SdlFreshstart: File/Folder removal fails without notification to user when a subfolder to be removed is open in Windows Explorer

### ISSUE THREAD

**Issue by plehn** [sdl/Sdl-Community#95]
Due to how C# handles file removal in some cases it seems the removal may fail about 50% of the time (at least in my tests on Windows 10), for a folder if a subfolder at least two levels below is opened in Windows Explorer. This may affect all files in the folder to be removed, or just some.
For instance: 
If the folder
**%AppData%\SDL\SDL Trados Studio\15.0.0.0**
is to be removed and the folder
**%AppData%\SDL\SDL Trados Studio\15.0.0.0\UserProfiles\Builtin**
is currently open in the Windows Explorer, the deletion may partially or even completely fail.

No warnings or errors displayed when file removal fails so the user may not be aware of this at all, that a reset has partially failed. If the issue cannot be resolved completely at least warnings should be given to the users, so they can then manually delete the affected folder.
Kind regards 
Peter

**Comment by cromica** [comment]
@andreaGhisa @paulfilkin Any comments on this issue?

**Comment by andreaGhisa** [comment]
I've logged an issue in Jira (SDLCOM-213) this issue will be fixed based on the availability of the team.

**Comment by andreaGhisa** [comment]
We fixed this issue. When the files are not deleted an warning message appears:
![image](https://user-images.githubusercontent.com/16224379/55934686-17e12380-5c3a-11e9-8327-fd6f0e76b043.png)
